config/routes.rb
Assignments::Application.routes.draw do

  get "welcome/index"

  get 'source_codes/:id/approve' => 'source_codes#approve', as: :approve
  get 'source_codes/:id/reject' => 'source_codes#reject', as: :reject

  get '/home' => 'home#index', as: :home
  root :to => 'welcome#index'

  get "uploader/create"

  mount Ckeditor::Engine => '/ckeditor'

  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  

  get '/projects/:project_id/contributions' => 'projects#contributions', as: :user_contributions 
  get '/assignments/start/:assignment_id' => 'submissions#start', as: :start_assignment 
  get '/projects/:project_id/start' => 'projects#participate', as: :start_project 
  get '/projects/:project_id/add_contribution' => 'projects#add_contribution', as: :add_contribution

  get '/projects/my_projects' => 'projects#my_projects', as: :my_projects

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users
  resources :profiles
  resources :contributions do 
    resources :comments
    resources :source_codes
    resources :attachments
  end

  resources :source_codes do
    resources :comments
  end
  resources :sessions
  resources :assignments do
    resources :attachments
  end

  resources :projects do
    resources :comments           # Each submission has_many comments
    resources :attachments        # Each submission has_many attachments
    resources :source_codes       # Each submission has_many source_codes
  end

  resources :submissions do
    resources :comments           # Each submission has_many comments
    resources :attachments        # Each submission has_many attachments
    resources :source_codes       # Each submission has_many source_codes
  end
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  include PublicActivity::Common  
  attr_accessible :category_id, :content, :difficulty, :level, :points, :tagline, :title

  belongs_to :category
  has_and_belongs_to_many :users

  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :comments, as: :commentable

  def complete!
    self.status = "COMPLETED"
    self.save
  end

#  def status
#    status
#  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def participate
    @project = Project.find(params[:project_id])
    @contribution = Contribution.new
    @project.users << current_user unless @project.users.include? current_user
    redirect_to project_path(@project), notice: "Joined the project"
  end

  def index
    @projects = Project.all
  end

  def my_projects
    @projects = current_user.projects
  end

  def show
    @project = Project.find(params[:id])
  end

  def contributions
    @project = Project.find(params[:project_id])
    @contributions = @project.contributions.where("user_id = ?", current_user.id)
    @user = current_user
  end

  def add_contribution
    @project = Project.find(params[:project_id])
    @contribution = Contribution.new
    @contribution.user = current_user
    @contribution.project = @project
    if @contribution.save
      @contribution.create_activity key: "contribution.newly_added"
    end
    @project.contributions << @contribution
    redirect_to edit_contribution_path(@contribution), notice: "New contribution Added. Please add the required source-codes and attachmetns alongs with its description for feedback"
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_header.html.erb
<div class="well">
  <% contribution = current_user.contributions.where(:project_id => model.id).first %>
  <% show_contribtuion = (contribution) ? true : false %>
  <h3 style="display:inline"><%= "Your contributions for " if show_contribtuion %><%= link_to model.title, user_contributions_path(model) %></h3> 
  <table class="table table-striped">
    <tr>
      <td width="70%">
        <div class="pagination pagination-large">
          <ul>
            <li>
              <span>Category <%= intensity_badge_tag(model.category.name) %></span>
            </li>
            <li>
              <span>Level <%= intensity_badge_tag(model.level) %></span>
            </li>
            <li>
              <span>Difficulty <%= intensity_badge_tag(model.difficulty) %></span>
            </li>
          </ul>
        </div>
      </td>
      <td style="vertical-align:top">
        <% if show_button %>
          <%= link_to "프로젝트에 참여하기", start_project_path(model.id), class: "btn btn-success" %>
        <% else %>
          <% contribution = current_user.contributions.where(:project_id => model.id).first %>
          <div class="pagination">
            <ul>
              <li>
                <%= link_to "Create a New Contribution", add_contribution_path(model.id), class: "btn btn-success" %>
              </li>
              <li>
                <%= link_to "See your contributions", user_contributions_path(model), class: "btn" if contribution %>
              </li>
            </ul>
          </div>
        <% end %>
      </td>
    </tr>
  </table>
  <p class="lead"><%= model.tagline %></p>
</div>

app/views/projects/contributions.html.erb
<%= render 'contributions/list', current_project: @project, user: @user %>

app/views/projects/index.html.erb
<h3>Projects Started so Far</h3>

<table class="table table-striped table-hover">
  <thead>
    <th>Category</th>
    <th>Level</th>
    <th>Difficulty</th>
    <th>Title</th>
    <th>Description</th>
    <th>Participation</th>
  </thead>
  <tbody>
    <% @projects.each do |prj| %>
      <tr>
        <td><%= prj.category.name %></td>
        <td><%= prj.level %></td>
        <td><%= prj.difficulty %></td>
        <td><%= link_to prj.title, project_path(prj) %></td>
        <td><%= prj.tagline %></td>
        <td>
          <% if current_user.contributions.where(:project_id => prj.id).any? %>
            <span class="label label-success">Have Contributed to the project</span>
          <% else %>
            <span class="label label">Not Participated Yet</span>
          <% end %>
        </td>
    <% end %>
  </tbody>
</table>

app/views/projects/my_projects.html.erb
<h3>Projects that you have participated in</h3>

<table class="table table-striped table-hover">
  <thead>
    <th>Category</th>
    <th>Level</th>
    <th>Difficulty</th>
    <th>Title</th>
    <th>Description</th>
    <th>Participation</th>
  </thead>
  <tbody>
    <% @projects.each do |prj| %>
      <tr>
        <td><%= prj.category.name %></td>
        <td><%= prj.level %></td>
        <td><%= prj.difficulty %></td>
        <td><%= link_to prj.title, project_path(prj) %></td>
        <td><%= prj.tagline %></td>
        <td>
          <% if current_user.contributions.where(:project_id => prj.id).any? %>
            <span class="label label-success">Have Contributed to the project</span>
          <% else %>
            <span class="label label">Not Participated Yet</span>
          <% end %>
        </td>
    <% end %>
  </tbody>
</table>

app/views/projects/participate.html.erb
<h1>Projects#participate</h1>
<p>Find me in app/views/projects/participate.html.erb</p>

app/views/projects/show.html.erb
<% if current_user.projects.where("project_id = ?", @project.id).any? %>
  <%= render "header", model: @project,  show_button: false, show_submission: false %>
<% else %>
  <%= render "header", model: @project,  show_button: true, show_submission: false %>
<% end %>

<h4>Detailed Instructions</h4>
<pre style="padding:2em; background-color:#FFFFFF"><%= @project.content.html_safe %></pre>

<% if @project.attachments.any? %>
  <%= render "attachments/list", current_model: @project, active_admin: false %>
<% end %>

<% if @project.contributions.any? %>
  <%= render "contributions/list", current_project: @project, user: nil %>
<% end %>

<h4>Comments</h4>
<%= render 'comments/comment', commentable: @project %>