config/routes.rb
Assignments::Application.routes.draw do

  get "welcome/index"

  get 'source_codes/:id/approve' => 'source_codes#approve', as: :approve
  get 'source_codes/:id/reject' => 'source_codes#reject', as: :reject

  get '/home' => 'home#index', as: :home
  root :to => 'welcome#index'

  get "uploader/create"

  mount Ckeditor::Engine => '/ckeditor'

  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  

  get '/projects/:project_id/contributions' => 'projects#contributions', as: :user_contributions 
  get '/assignments/start/:assignment_id' => 'submissions#start', as: :start_assignment 
  get '/projects/:project_id/start' => 'projects#participate', as: :start_project 
  get '/projects/:project_id/add_contribution' => 'projects#add_contribution', as: :add_contribution

  get '/projects/my_projects' => 'projects#my_projects', as: :my_projects

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users
  resources :profiles
  resources :contributions do 
    resources :comments
    resources :source_codes
    resources :attachments
  end

  resources :source_codes do
    resources :comments
  end
  resources :sessions
  resources :assignments do
    resources :attachments
  end

  resources :projects do
    resources :comments           # Each submission has_many comments
    resources :attachments        # Each submission has_many attachments
    resources :source_codes       # Each submission has_many source_codes
  end

  resources :submissions do
    resources :comments           # Each submission has_many comments
    resources :attachments        # Each submission has_many attachments
    resources :source_codes       # Each submission has_many source_codes
  end
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :full_name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  include PublicActivity::Common  

  # Not accessable is :completed, :completed_at
  attr_accessible :content, :due_date, :points, :tagline, :title, :level, :difficulty, :category_id

  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :submissions, dependent: :destroy
  belongs_to :category

  #accepts_nested_attributes_for :category

  # Validations
  validates_inclusion_of :difficulty, :level, in: 1..3, message: "Should be an integer from 1 ~ 3"
  validates_presence_of :content, :tagline, :title, :points, :level, :difficulty, :category

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :filename, :filename_cache

  belongs_to :attachable, polymorphic: true
  mount_uploader :filename, AttachmentUploader  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :assignment_id, :name
  has_many :assignment
  has_many :projects

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include PublicActivity::Common

  attr_accessible :commentable_id, :commentable_type, :content

  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates_presence_of :user
  validates_presence_of :content

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  include PublicActivity::Common  

  attr_accessible :description, :project_id, :user_id, :status

  belongs_to :user
  belongs_to :project

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :source_codes, as: :source_codeable, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  
  validates_presence_of :user, :project


end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :bio, :interests, :tagline, :avatar
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/models/project.rb
class Project < ActiveRecord::Base
  include PublicActivity::Common  
  attr_accessible :category_id, :content, :difficulty, :level, :points, :tagline, :title

  belongs_to :category
  has_and_belongs_to_many :users

  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :comments, as: :commentable

  def complete!
    self.status = "COMPLETED"
    self.save
  end

#  def status
#    status
#  end
end

app/models/source_code.rb
class SourceCode < ActiveRecord::Base
  attr_accessible :content

  belongs_to :source_codeable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable

  validates_presence_of :user
  validates_presence_of :name
#  validates_inclusion_of :status, in: %w(pending requires_modification completed)

  scope :latest, order("created_at desc")
  scope :pending, where(:status => :pending)
  scope :rejected, where(:status => :requires_modification)
  scope :completed, where(:status => :completed)
  mount_uploader :content, SourceCodeUploader

  def reject!
    self.status = :requires_modification
    self.save
  end

  def approve!
    self.status = :completed
    self.save
    self.source_codeable.complete!
  end
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  attr_accessible :assignment_id, :feedback, :user_id, :completed, :completed_at

  belongs_to :user
  belongs_to :assignment

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :source_codes, as: :source_codeable, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy


  # Validations
  validates_presence_of :user, :assignment

  def complete!
    self.completed = true
    self.completed_at = Time.now
    self.user.points += self.assignment.points
    self.user.save
    self.save
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :class_id, :department, :email, :first_name, :last_name, 
                  :password, :password_confirmation, :university, :about_me

  before_create { generate_token(:auth_token) }

  validates_presence_of :class_id, :first_name, :last_name, :university, :department


  has_many :submissions, dependent: :destroy
  has_many :comments        # TODO
  has_many :source_codes, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_and_belongs_to_many :projects
  has_many :contributions


  def full_name
    first_name + ' ' + last_name
  end

  def send_password_reset

  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/controllers/contributions_controller.rb
# encoding: UTF-8

class ContributionsController < ApplicationController

  before_filter :authenticate_user

  def show
    @contribution = Contribution.find(params[:id])
  end


  def edit
    @contribution = Contribution.find(params[:id])
  end

  def update
    @contribution = Contribution.find(params[:id])
    if @contribution.update_attributes(params[:contribution])
      redirect_to contribution_path(@contribution), notice: "Successfully Edited"
    else
      render :edit
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper


  def intensity_badge_tag(difficulty)
    return unless difficulty

    class_name = case difficulty
                 when 1 then 'info'
                 when 2 then 'success'
                 when 3 then 'important'
                 end
    content_tag :span, difficulty, class: "badge badge-#{class_name}"
  end

  def number_badge(num)
    return unless num

    content_tag :span, num, class: "badge badge-success"
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contributions/_list.html.erb
<div class="contributions_index">
  <div class="well">

    <% if user.nil? %>
      <h4>List of Contributions to the Project</h4>
      <% contributions = current_project.contributions.order("created_at desc") %>
    <% else %>
      <h4>Your Contribtuions to the project </h4>
      <% contributions = current_project.contributions.where("user_id = ?", user.id).order("created_at desc") %>
    <% end %>

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Contribution</th>
          <th> Status </th>
          <th>By </th>
          <th>View </th>
        </tr>
      </thead>
      <tbody>

        <% contributions.each do |contrib| %>
          <tr>
            <td>
              <%= truncate(contrib.description) %>
            </td>
            <td>
              <% if contrib.status == "completed" %>
                <span class="label label-success">Completed</span>
              <% elsif contrib.status == "pending" %> 
                <span class="label">Pending</span>
              <% else %> 
                <span class="label label-warning">Requires Modification</span>
              <% end %>
            </td>
            <td>
              <% if contrib.user %>
                <%= link_to contrib.user.full_name, profile_path(contrib.user.profile) %>
              <% end %>
            </td>
            <td>
              <%= link_to "View", contribution_path(contrib), class: 'btn btn-small' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/contributions/edit.html.erb
<h3> Your Contribution for <%= @contribution.project.title %> </h3>


<div id="source_codes">
  <% if @contribution.source_codes.any? %>
    <%= render 'source_codes/index', current_model: @contribution %>
  <% else %>
    <div class="well" id="didnt_upload">
      <p class="lead">You haven't uploaded any source-codes yet. Upload them to be reviewed by admin</p>
    </div>
  <% end %>
</div>


<%= render "attachments/list", current_model: @contribution, active_admin: false %> 

<div class="span4">
<%= render 'source_codes/uploader', current_model: @contribution %>
</div>
<div class="span4">
<%= render "attachments/uploader", current_model: @contribution, active_admin: false %>
</div>

<h4>Description</h4>
<strong> Please include a full detailed description of your contribution, including references to your source-code and other attachments related to the contribution </strong>
<div class="well">
  <%= form_for @contribution do |f| %>
    <%= f.text_area :description, rows: "10", col: "40", class: "field span5" %>

    <div class="control-group">
      <div class="controls">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/contributions/show.html.erb
<h3>Contribution for <%= @contribution.project.title %></h3>
<%= link_to "Edit this Contribution", edit_contribution_path(@contribution), class: "btn" %>


<h4>Description</h4>
<div class="well">
  <p class="lead"><%= @contribution.description %></p>
</div>

<% if @contribution.source_codes.any? %>
  <%= render 'source_codes/index', current_model: @contribution %>
<% else %>
  <div class="well">
    <p class="lead">You haven't uploaded any source-codes yet. Upload them to be be reviewed by admin</p>
  </div>
<% end %>

<%= render 'attachments/list', current_model: @contribution, active_admin: false %>

<h4> Commentds and Feedback </h4>
<%= render 'comments/comment', commentable: @contribution %>